apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: debug
spec:
  provider:
    aws:
      region: ap-northeast-1
      service: SecretsManager

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: testing-pod-secret
  namespace: debug
spec:
  secretStoreRef:
    name: aws-secret-store
    kind: SecretStore
  target:
    name: testing-secret  # name of the k8s Secret to be created
    creationPolicy: Owner
  dataFrom:
  - extract:
     key: testing-pod-secret